### ISSUE TITLE
[Feature]Add option for different output folder names than rom folder names

### ISSUE THREAD

**Issue by joyrider3774** [anibaldeboni/screech#2]
Would it be possible to add per system another folder name that can be used as as the output folder ?

Like if that setting is present use that foldername as output foldername instead of the rom / system folder name. 

I like to try this on muos but on muos folders for roms are not fixed and the folders for assets can be completly different than the rom foldername. By adding such option it could potentially work for muos and if you make that output folder name optional nothing would change from how it currently works and if we provide the folder name in the config yaml it would always use that (sub)foldername

**Comment by joyrider3774** [comment]
perhaps my issue is not that clear but basically i want an alternate name to be used for the replacement of %SYSTEM% var which we can define per system (so using something different than rom dir as output dir)

**Comment by anibaldeboni** [comment]
> perhaps my issue is not that clear but basically i want an alternate name to be used for the replacement of %SYSTEM% var which we can define per system (so using something different than rom dir as output dir)

I'm not getting what you want, could you give some examples of what you may want to use as the value of %SYSTEM%?

**Comment by joyrider3774** [comment]
It's simple In screech.yaml i want to define an optional alternate outputdirectory like so:

```
systems:
- dir: SFC
    id: "4"
    name: Super Nintendo (SNES)
    outputdir: Nintendo SNES-SFC
- dir: nes
    id: "3"
    name: NES (Famicom)
   outputdir: Nintendo NES-Famicom
```

and i want %SYSTEM% to be replaced with the value of outputdir or can make a new variable %OUTPUTDIR%

The reason this is needed for muos (rg35XX line) is that muos uses different names for the rom folders and the folders where it saves the assets

**Comment by joyrider3774** [comment]
if this is not possible potetially add a %NAME% variable that would replace %NAME% with name from config and i'll abuse the name variable for this :)

**Comment by anibaldeboni** [comment]
Now I get it. I'll move this feature to the backlog

**Comment by anibaldeboni** [comment]
Hi @joyrider3774 I developed the feature to set a custom `%SYSTEM%` per system. It will be available in the next release.
